# Generated by Django 3.2.4 on 2021-11-29 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20211129_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='end_time',
            new_name='shift_end',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='start_time',
            new_name='shift_start',
        ),
    ]
