# Generated by Django 3.2.4 on 2021-11-29 19:30

from django.db import migrations
import django.db.models.deletion
import persons.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20211129_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='owner',
            field=persons.utils.fields.ShiftsField(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='persons.person'),
        ),
    ]
