# Generated by Django 3.2.9 on 2021-11-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_auto_20211130_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
