# Generated by Django 3.2.9 on 2021-11-29 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_auto_20211130_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='middayshift',
            name='on_duty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_midday_shifts', to='persons.person'),
        ),
        migrations.AlterField(
            model_name='morningshift',
            name='on_duty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_moning_shifts', to='persons.person'),
        ),
        migrations.AlterField(
            model_name='nightshift',
            name='on_duty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_night_shifts', to='persons.person'),
        ),
    ]
