# Generated by Django 3.2.9 on 2021-11-29 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0009_auto_20211130_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifts',
            name='midday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midday_shifts', to='persons.middayshift', verbose_name='16-24'),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='morning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morning_shifts', to='persons.morningshift', verbose_name='08-14'),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='nigth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='night_shifts', to='persons.nightshift', verbose_name='0-8'),
        ),
    ]
