# Generated by Django 3.2.9 on 2021-11-29 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0010_auto_20211130_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifts',
            name='nigth',
        ),
        migrations.AddField(
            model_name='shifts',
            name='night',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='night_shifts', to='persons.nightshift'),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='midday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='midday_shifts', to='persons.middayshift'),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='morning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='morning_shifts', to='persons.morningshift'),
        ),
    ]
